/** NOTE: This file is synthesized by /Path/To/Alton/Parser/_Generation/ParserGenerator.py */
# include <ETC/BareboneMacros.hpp>
# include <Parser/Parser.hpp>
# include <Parser/ParseHelper.hpp>


namespace Alton
{
	namespace Parser
	{
		void ParseHelper::initialize_rules ()
		{
			// --- Head ---
			// -- First, HUGE -- 
			rules.reserve (103);
			rules.push_back (ParseRule (Symbol::nterm_start, 1));
			rules.push_back (ParseRule (Symbol::nterm_module_space, 2));
			rules.push_back (ParseRule (Symbol::nterm_module_space, 1));
			rules.push_back (ParseRule (Symbol::nterm_module_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_module_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_module_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_interface, 3));
			rules.push_back (ParseRule (Symbol::nterm_declare, 2));
			rules.push_back (ParseRule (Symbol::nterm_declare, 2));
			rules.push_back (ParseRule (Symbol::nterm_declare, 2));
			rules.push_back (ParseRule (Symbol::nterm_declare, 2));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_type, 1));
			rules.push_back (ParseRule (Symbol::nterm_defargs, 3));
			rules.push_back (ParseRule (Symbol::nterm_defargs, 2));
			rules.push_back (ParseRule (Symbol::nterm_defunion, 3));
			rules.push_back (ParseRule (Symbol::nterm_defunion, 1));
			rules.push_back (ParseRule (Symbol::nterm_defunion, 1));
			rules.push_back (ParseRule (Symbol::nterm_defassignunion, 5));
			rules.push_back (ParseRule (Symbol::nterm_defassignunion, 3));
			rules.push_back (ParseRule (Symbol::nterm_item, 3));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_item, 1));
			rules.push_back (ParseRule (Symbol::nterm_paren_oper, 2));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_any_oper, 1));
			rules.push_back (ParseRule (Symbol::nterm_union, 3));
			rules.push_back (ParseRule (Symbol::nterm_union, 1));
			rules.push_back (ParseRule (Symbol::nterm_call_item, 4));
			rules.push_back (ParseRule (Symbol::nterm_call_item, 4));
			rules.push_back (ParseRule (Symbol::nterm_call_item, 3));
			rules.push_back (ParseRule (Symbol::nterm_array_access, 4));
			rules.push_back (ParseRule (Symbol::nterm_array, 3));
			rules.push_back (ParseRule (Symbol::nterm_array, 2));
			rules.push_back (ParseRule (Symbol::nterm_location, 3));
			rules.push_back (ParseRule (Symbol::nterm_location, 1));
			rules.push_back (ParseRule (Symbol::nterm_code, 3));
			rules.push_back (ParseRule (Symbol::nterm_code, 2));
			rules.push_back (ParseRule (Symbol::nterm_stmtunion, 3));
			rules.push_back (ParseRule (Symbol::nterm_stmtunion, 1));
			rules.push_back (ParseRule (Symbol::nterm_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_simple_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_simple_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_simple_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_simple_stmt, 1));
			rules.push_back (ParseRule (Symbol::nterm_goto_stmt, 3));
			rules.push_back (ParseRule (Symbol::nterm_seg_stmt, 3));
			rules.push_back (ParseRule (Symbol::nterm_vardef, 1));
			rules.push_back (ParseRule (Symbol::nterm_vardef, 3));
			rules.push_back (ParseRule (Symbol::nterm_if, 3));
			rules.push_back (ParseRule (Symbol::nterm_if, 3));
			rules.push_back (ParseRule (Symbol::nterm_if, 3));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 5));
			rules.push_back (ParseRule (Symbol::nterm_if, 3));
			rules.push_back (ParseRule (Symbol::nterm_if, 3));
			rules.push_back (ParseRule (Symbol::nterm_if, 3));
			rules.push_back (ParseRule (Symbol::nterm_single_arg, 3));
			rules.push_back (ParseRule (Symbol::nterm_single_arg, 3));
			rules.push_back (ParseRule (Symbol::nterm_if_else, 5));
			rules.push_back (ParseRule (Symbol::nterm_if_else, 5));
			rules.push_back (ParseRule (Symbol::nterm_if_else, 5));
			rules.push_back (ParseRule (Symbol::nterm_if_else, 3));
			rules.push_back (ParseRule (Symbol::nterm_shader, 4));
			rules.push_back (ParseRule (Symbol::nterm_module, 4));
			rules.push_back (ParseRule (Symbol::nterm_module, 3));
			
		}

		void ParseHelper::initialize_parse_table ()
		{
			// --- Head ---
			// -- Second --
			const Natural state_count = 153;
			const Natural symbol_count = Symbol::count;
			table.resize (state_count);

			// --- Body ---
			// -- Third, HUGE -- 
			table [0].resize (symbol_count);
			table [0] [Symbol::identifier].override (ParseOperationType::shift, 1);
			table [0] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [0] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [0] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [0] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [0] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [0] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [0] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [0] [Symbol::keyword_goto].override (ParseOperationType::shift, 9);
			table [0] [Symbol::keyword_graphic].override (ParseOperationType::shift, 10);
			table [0] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [0] [Symbol::nterm_start].override (ParseOperationType::shift, 12);
			table [0] [Symbol::nterm_module_space].override (ParseOperationType::go_to, 13);
			table [0] [Symbol::nterm_module_item].override (ParseOperationType::go_to, 14);
			table [0] [Symbol::nterm_interface].override (ParseOperationType::go_to, 15);
			table [0] [Symbol::nterm_shader].override (ParseOperationType::go_to, 19);
			table [0] [Symbol::nterm_module].override (ParseOperationType::go_to, 20);
			table [0] [Symbol::nterm_declare].override (ParseOperationType::go_to, 16);
			table [0] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [0] [Symbol::nterm_location].override (ParseOperationType::go_to, 18);
			table [1].resize (symbol_count);
			table [1] [Symbol::lbrack].override (ParseOperationType::shift, 21);
			table [1] [Symbol::identifier].override (ParseOperationType::reduce, 62);
			table [1] [Symbol::oper_dot].override (ParseOperationType::shift, 22);
			table [1] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 62);
			table [2].resize (symbol_count);
			table [2] [Symbol::identifier].override (ParseOperationType::reduce, 11);
			table [2] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 11);
			table [3].resize (symbol_count);
			table [3] [Symbol::identifier].override (ParseOperationType::reduce, 16);
			table [3] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 16);
			table [4].resize (symbol_count);
			table [4] [Symbol::identifier].override (ParseOperationType::reduce, 13);
			table [4] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 13);
			table [5].resize (symbol_count);
			table [5] [Symbol::identifier].override (ParseOperationType::reduce, 17);
			table [5] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 17);
			table [6].resize (symbol_count);
			table [6] [Symbol::identifier].override (ParseOperationType::reduce, 14);
			table [6] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 14);
			table [7].resize (symbol_count);
			table [7] [Symbol::identifier].override (ParseOperationType::reduce, 15);
			table [7] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 15);
			table [8].resize (symbol_count);
			table [8] [Symbol::identifier].override (ParseOperationType::shift, 23);
			table [8] [Symbol::keyword_underscore].override (ParseOperationType::shift, 24);
			table [9].resize (symbol_count);
			table [9] [Symbol::identifier].override (ParseOperationType::reduce, 18);
			table [9] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 18);
			table [10].resize (symbol_count);
			table [10] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [10] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [10] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [10] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [10] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [10] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [10] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [10] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [10] [Symbol::keyword_goto].override (ParseOperationType::shift, 9);
			table [10] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [10] [Symbol::nterm_declare].override (ParseOperationType::go_to, 26);
			table [10] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [10] [Symbol::nterm_location].override (ParseOperationType::go_to, 18);
			table [11].resize (symbol_count);
			table [11] [Symbol::identifier].override (ParseOperationType::reduce, 12);
			table [11] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 12);
			table [12].resize (symbol_count);
			table [12] [Symbol::ending].override (ParseOperationType::accept, 0);
			table [13].resize (symbol_count);
			table [13] [Symbol::ending].override (ParseOperationType::reduce, 0);
			table [14].resize (symbol_count);
			table [14] [Symbol::identifier].override (ParseOperationType::shift, 1);
			table [14] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [14] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [14] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [14] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [14] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [14] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [14] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [14] [Symbol::keyword_goto].override (ParseOperationType::shift, 9);
			table [14] [Symbol::keyword_graphic].override (ParseOperationType::shift, 10);
			table [14] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [14] [Symbol::nterm_module_space].override (ParseOperationType::go_to, 27);
			table [14] [Symbol::nterm_module_item].override (ParseOperationType::go_to, 14);
			table [14] [Symbol::nterm_interface].override (ParseOperationType::go_to, 15);
			table [14] [Symbol::nterm_shader].override (ParseOperationType::go_to, 19);
			table [14] [Symbol::nterm_module].override (ParseOperationType::go_to, 20);
			table [14] [Symbol::nterm_declare].override (ParseOperationType::go_to, 16);
			table [14] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [14] [Symbol::nterm_location].override (ParseOperationType::go_to, 18);
			table [14] [Symbol::ending].override (ParseOperationType::reduce, 2);
			table [15].resize (symbol_count);
			table [15] [Symbol::identifier].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_shader].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_float].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_bool].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_void].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_int].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_nat].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_var].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_goto].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::keyword_interface].override (ParseOperationType::reduce, 3);
			table [15] [Symbol::ending].override (ParseOperationType::reduce, 3);
			table [16].resize (symbol_count);
			table [16] [Symbol::lparen].override (ParseOperationType::shift, 28);
			table [16] [Symbol::nterm_defargs].override (ParseOperationType::go_to, 29);
			table [17].resize (symbol_count);
			table [17] [Symbol::identifier].override (ParseOperationType::shift, 30);
			table [17] [Symbol::keyword_underscore].override (ParseOperationType::shift, 31);
			table [18].resize (symbol_count);
			table [18] [Symbol::identifier].override (ParseOperationType::reduce, 19);
			table [18] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 19);
			table [19].resize (symbol_count);
			table [19] [Symbol::identifier].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_shader].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_float].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_bool].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_void].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_int].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_nat].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_var].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_goto].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::keyword_interface].override (ParseOperationType::reduce, 4);
			table [19] [Symbol::ending].override (ParseOperationType::reduce, 4);
			table [20].resize (symbol_count);
			table [20] [Symbol::identifier].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_shader].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_float].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_bool].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_void].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_int].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_nat].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_var].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_goto].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::keyword_interface].override (ParseOperationType::reduce, 5);
			table [20] [Symbol::ending].override (ParseOperationType::reduce, 5);
			table [21].resize (symbol_count);
			table [21] [Symbol::rbrack].override (ParseOperationType::shift, 32);
			table [21] [Symbol::identifier].override (ParseOperationType::shift, 1);
			table [21] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [21] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [21] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [21] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [21] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [21] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [21] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [21] [Symbol::keyword_goto].override (ParseOperationType::shift, 9);
			table [21] [Symbol::keyword_graphic].override (ParseOperationType::shift, 10);
			table [21] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [21] [Symbol::nterm_module_space].override (ParseOperationType::go_to, 33);
			table [21] [Symbol::nterm_module_item].override (ParseOperationType::go_to, 14);
			table [21] [Symbol::nterm_interface].override (ParseOperationType::go_to, 15);
			table [21] [Symbol::nterm_shader].override (ParseOperationType::go_to, 19);
			table [21] [Symbol::nterm_module].override (ParseOperationType::go_to, 20);
			table [21] [Symbol::nterm_declare].override (ParseOperationType::go_to, 16);
			table [21] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [21] [Symbol::nterm_location].override (ParseOperationType::go_to, 18);
			table [22].resize (symbol_count);
			table [22] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [22] [Symbol::nterm_location].override (ParseOperationType::go_to, 34);
			table [23].resize (symbol_count);
			table [23] [Symbol::lparen].override (ParseOperationType::reduce, 9);
			table [24].resize (symbol_count);
			table [24] [Symbol::lparen].override (ParseOperationType::reduce, 10);
			table [25].resize (symbol_count);
			table [25] [Symbol::identifier].override (ParseOperationType::reduce, 62);
			table [25] [Symbol::oper_dot].override (ParseOperationType::shift, 22);
			table [25] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 62);
			table [26].resize (symbol_count);
			table [26] [Symbol::lparen].override (ParseOperationType::shift, 28);
			table [26] [Symbol::nterm_defargs].override (ParseOperationType::go_to, 35);
			table [27].resize (symbol_count);
			table [27] [Symbol::ending].override (ParseOperationType::reduce, 1);
			table [28].resize (symbol_count);
			table [28] [Symbol::rparen].override (ParseOperationType::shift, 36);
			table [28] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [28] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [28] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [28] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [28] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [28] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [28] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [28] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [28] [Symbol::keyword_goto].override (ParseOperationType::shift, 9);
			table [28] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [28] [Symbol::nterm_declare].override (ParseOperationType::go_to, 37);
			table [28] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [28] [Symbol::nterm_location].override (ParseOperationType::go_to, 18);
			table [28] [Symbol::nterm_defunion].override (ParseOperationType::go_to, 38);
			table [28] [Symbol::nterm_defassignunion].override (ParseOperationType::go_to, 39);
			table [29].resize (symbol_count);
			table [29] [Symbol::lscope].override (ParseOperationType::shift, 40);
			table [29] [Symbol::nterm_code].override (ParseOperationType::go_to, 41);
			table [30].resize (symbol_count);
			table [30] [Symbol::lparen].override (ParseOperationType::reduce, 7);
			table [31].resize (symbol_count);
			table [31] [Symbol::lparen].override (ParseOperationType::reduce, 8);
			table [32].resize (symbol_count);
			table [32] [Symbol::identifier].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_shader].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_float].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_bool].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_void].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_int].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_nat].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_var].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_goto].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::keyword_interface].override (ParseOperationType::reduce, 102);
			table [32] [Symbol::ending].override (ParseOperationType::reduce, 102);
			table [33].resize (symbol_count);
			table [33] [Symbol::rbrack].override (ParseOperationType::shift, 42);
			table [34].resize (symbol_count);
			table [34] [Symbol::identifier].override (ParseOperationType::reduce, 61);
			table [34] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 61);
			table [35].resize (symbol_count);
			table [35] [Symbol::lscope].override (ParseOperationType::shift, 40);
			table [35] [Symbol::nterm_code].override (ParseOperationType::go_to, 43);
			table [36].resize (symbol_count);
			table [36] [Symbol::lscope].override (ParseOperationType::reduce, 21);
			table [37].resize (symbol_count);
			table [37] [Symbol::rparen].override (ParseOperationType::reduce, 23);
			table [37] [Symbol::oper_union].override (ParseOperationType::shift, 44);
			table [37] [Symbol::oper_assign].override (ParseOperationType::shift, 45);
			table [38].resize (symbol_count);
			table [38] [Symbol::rparen].override (ParseOperationType::shift, 46);
			table [39].resize (symbol_count);
			table [39] [Symbol::rparen].override (ParseOperationType::reduce, 24);
			table [40].resize (symbol_count);
			table [40] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [40] [Symbol::rscope].override (ParseOperationType::shift, 48);
			table [40] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [40] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [40] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [40] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [40] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [40] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [40] [Symbol::statement_end].override (ParseOperationType::shift, 54);
			table [40] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [40] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [40] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [40] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [40] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [40] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [40] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [40] [Symbol::keyword_goto].override (ParseOperationType::shift, 55);
			table [40] [Symbol::keyword_seg].override (ParseOperationType::shift, 56);
			table [40] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [40] [Symbol::keyword_while].override (ParseOperationType::shift, 57);
			table [40] [Symbol::keyword_if].override (ParseOperationType::shift, 58);
			table [40] [Symbol::nterm_declare].override (ParseOperationType::go_to, 59);
			table [40] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [40] [Symbol::nterm_location].override (ParseOperationType::go_to, 64);
			table [40] [Symbol::nterm_item].override (ParseOperationType::go_to, 60);
			table [40] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [40] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [40] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [40] [Symbol::nterm_stmtunion].override (ParseOperationType::go_to, 65);
			table [40] [Symbol::nterm_stmt].override (ParseOperationType::go_to, 66);
			table [40] [Symbol::nterm_if].override (ParseOperationType::go_to, 71);
			table [40] [Symbol::nterm_if_else].override (ParseOperationType::go_to, 72);
			table [40] [Symbol::nterm_simple_stmt].override (ParseOperationType::go_to, 67);
			table [40] [Symbol::nterm_goto_stmt].override (ParseOperationType::go_to, 68);
			table [40] [Symbol::nterm_seg_stmt].override (ParseOperationType::go_to, 69);
			table [40] [Symbol::nterm_vardef].override (ParseOperationType::go_to, 70);
			table [41].resize (symbol_count);
			table [41] [Symbol::identifier].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_shader].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_float].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_bool].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_void].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_int].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_nat].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_var].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_goto].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::keyword_interface].override (ParseOperationType::reduce, 6);
			table [41] [Symbol::ending].override (ParseOperationType::reduce, 6);
			table [42].resize (symbol_count);
			table [42] [Symbol::identifier].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_shader].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_float].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_bool].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_void].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_int].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_nat].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_var].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_goto].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::keyword_interface].override (ParseOperationType::reduce, 101);
			table [42] [Symbol::ending].override (ParseOperationType::reduce, 101);
			table [43].resize (symbol_count);
			table [43] [Symbol::identifier].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_shader].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_float].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_bool].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_void].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_int].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_nat].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_var].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_goto].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::keyword_interface].override (ParseOperationType::reduce, 100);
			table [43] [Symbol::ending].override (ParseOperationType::reduce, 100);
			table [44].resize (symbol_count);
			table [44] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [44] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [44] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [44] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [44] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [44] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [44] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [44] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [44] [Symbol::keyword_goto].override (ParseOperationType::shift, 9);
			table [44] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [44] [Symbol::nterm_declare].override (ParseOperationType::go_to, 37);
			table [44] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [44] [Symbol::nterm_location].override (ParseOperationType::go_to, 18);
			table [44] [Symbol::nterm_defunion].override (ParseOperationType::go_to, 73);
			table [44] [Symbol::nterm_defassignunion].override (ParseOperationType::go_to, 39);
			table [45].resize (symbol_count);
			table [45] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [45] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [45] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [45] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [45] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [45] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [45] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [45] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [45] [Symbol::nterm_item].override (ParseOperationType::go_to, 74);
			table [45] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [45] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [45] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [46].resize (symbol_count);
			table [46] [Symbol::lscope].override (ParseOperationType::reduce, 20);
			table [47].resize (symbol_count);
			table [47] [Symbol::oper_plus].override (ParseOperationType::shift, 76);
			table [47] [Symbol::oper_minus].override (ParseOperationType::shift, 77);
			table [47] [Symbol::oper_star].override (ParseOperationType::shift, 78);
			table [47] [Symbol::oper_slash].override (ParseOperationType::shift, 79);
			table [47] [Symbol::oper_percent].override (ParseOperationType::shift, 80);
			table [47] [Symbol::oper_left_left].override (ParseOperationType::shift, 81);
			table [47] [Symbol::oper_right_right].override (ParseOperationType::shift, 82);
			table [47] [Symbol::oper_accent].override (ParseOperationType::shift, 83);
			table [47] [Symbol::oper_stand].override (ParseOperationType::shift, 84);
			table [47] [Symbol::oper_ampersand].override (ParseOperationType::shift, 85);
			table [47] [Symbol::oper_equal].override (ParseOperationType::shift, 86);
			table [47] [Symbol::oper_not_equal].override (ParseOperationType::shift, 87);
			table [47] [Symbol::oper_less_than].override (ParseOperationType::shift, 88);
			table [47] [Symbol::oper_less_than_equal].override (ParseOperationType::shift, 89);
			table [47] [Symbol::oper_greater_than].override (ParseOperationType::shift, 90);
			table [47] [Symbol::oper_greater_than_equal].override (ParseOperationType::shift, 91);
			table [47] [Symbol::nterm_paren_oper].override (ParseOperationType::go_to, 92);
			table [47] [Symbol::nterm_any_oper].override (ParseOperationType::go_to, 93);
			table [48].resize (symbol_count);
			table [48] [Symbol::identifier].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_shader].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_float].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_bool].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_void].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_int].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_nat].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_var].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_goto].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::keyword_interface].override (ParseOperationType::reduce, 64);
			table [48] [Symbol::ending].override (ParseOperationType::reduce, 64);
			table [49].resize (symbol_count);
			table [49] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [49] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [49] [Symbol::rbrack].override (ParseOperationType::shift, 94);
			table [49] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [49] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [49] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [49] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [49] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [49] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [49] [Symbol::nterm_item].override (ParseOperationType::go_to, 95);
			table [49] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [49] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [49] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [49] [Symbol::nterm_union].override (ParseOperationType::go_to, 96);
			table [50].resize (symbol_count);
			table [50] [Symbol::lparen].override (ParseOperationType::reduce, 28);
			table [50] [Symbol::rscope].override (ParseOperationType::reduce, 28);
			table [50] [Symbol::lbrack].override (ParseOperationType::reduce, 28);
			table [50] [Symbol::statement_end].override (ParseOperationType::reduce, 28);
			table [51].resize (symbol_count);
			table [51] [Symbol::lparen].override (ParseOperationType::reduce, 29);
			table [51] [Symbol::rscope].override (ParseOperationType::reduce, 29);
			table [51] [Symbol::lbrack].override (ParseOperationType::reduce, 29);
			table [51] [Symbol::statement_end].override (ParseOperationType::reduce, 29);
			table [52].resize (symbol_count);
			table [52] [Symbol::lparen].override (ParseOperationType::reduce, 30);
			table [52] [Symbol::rscope].override (ParseOperationType::reduce, 30);
			table [52] [Symbol::lbrack].override (ParseOperationType::reduce, 30);
			table [52] [Symbol::statement_end].override (ParseOperationType::reduce, 30);
			table [53].resize (symbol_count);
			table [53] [Symbol::lparen].override (ParseOperationType::reduce, 31);
			table [53] [Symbol::rscope].override (ParseOperationType::reduce, 31);
			table [53] [Symbol::lbrack].override (ParseOperationType::reduce, 31);
			table [53] [Symbol::statement_end].override (ParseOperationType::reduce, 31);
			table [54].resize (symbol_count);
			table [54] [Symbol::rscope].override (ParseOperationType::reduce, 70);
			table [54] [Symbol::statement_end].override (ParseOperationType::reduce, 70);
			table [55].resize (symbol_count);
			table [55] [Symbol::identifier].override (ParseOperationType::reduce, 18);
			table [55] [Symbol::oper_colon].override (ParseOperationType::shift, 97);
			table [55] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 18);
			table [56].resize (symbol_count);
			table [56] [Symbol::oper_colon].override (ParseOperationType::shift, 98);
			table [57].resize (symbol_count);
			table [57] [Symbol::lparen].override (ParseOperationType::shift, 99);
			table [57] [Symbol::nterm_single_arg].override (ParseOperationType::go_to, 100);
			table [58].resize (symbol_count);
			table [58] [Symbol::lparen].override (ParseOperationType::shift, 99);
			table [58] [Symbol::nterm_single_arg].override (ParseOperationType::go_to, 101);
			table [59].resize (symbol_count);
			table [59] [Symbol::rscope].override (ParseOperationType::reduce, 77);
			table [59] [Symbol::statement_end].override (ParseOperationType::reduce, 77);
			table [59] [Symbol::oper_assign].override (ParseOperationType::shift, 102);
			table [60].resize (symbol_count);
			table [60] [Symbol::lparen].override (ParseOperationType::shift, 103);
			table [60] [Symbol::rscope].override (ParseOperationType::reduce, 74);
			table [60] [Symbol::lbrack].override (ParseOperationType::shift, 104);
			table [60] [Symbol::statement_end].override (ParseOperationType::reduce, 74);
			table [61].resize (symbol_count);
			table [61] [Symbol::lparen].override (ParseOperationType::reduce, 32);
			table [61] [Symbol::rscope].override (ParseOperationType::reduce, 32);
			table [61] [Symbol::lbrack].override (ParseOperationType::reduce, 32);
			table [61] [Symbol::statement_end].override (ParseOperationType::reduce, 32);
			table [62].resize (symbol_count);
			table [62] [Symbol::lparen].override (ParseOperationType::reduce, 33);
			table [62] [Symbol::rscope].override (ParseOperationType::reduce, 33);
			table [62] [Symbol::lbrack].override (ParseOperationType::reduce, 33);
			table [62] [Symbol::statement_end].override (ParseOperationType::reduce, 33);
			table [63].resize (symbol_count);
			table [63] [Symbol::lparen].override (ParseOperationType::reduce, 34);
			table [63] [Symbol::rscope].override (ParseOperationType::reduce, 34);
			table [63] [Symbol::lbrack].override (ParseOperationType::reduce, 34);
			table [63] [Symbol::statement_end].override (ParseOperationType::reduce, 34);
			table [64].resize (symbol_count);
			table [64] [Symbol::lparen].override (ParseOperationType::reduce, 35);
			table [64] [Symbol::rscope].override (ParseOperationType::reduce, 35);
			table [64] [Symbol::lbrack].override (ParseOperationType::reduce, 35);
			table [64] [Symbol::identifier].override (ParseOperationType::reduce, 19);
			table [64] [Symbol::statement_end].override (ParseOperationType::reduce, 35);
			table [64] [Symbol::keyword_underscore].override (ParseOperationType::reduce, 19);
			table [65].resize (symbol_count);
			table [65] [Symbol::rscope].override (ParseOperationType::shift, 105);
			table [66].resize (symbol_count);
			table [66] [Symbol::rscope].override (ParseOperationType::reduce, 66);
			table [66] [Symbol::statement_end].override (ParseOperationType::shift, 106);
			table [67].resize (symbol_count);
			table [67] [Symbol::rscope].override (ParseOperationType::reduce, 69);
			table [67] [Symbol::statement_end].override (ParseOperationType::reduce, 69);
			table [68].resize (symbol_count);
			table [68] [Symbol::rscope].override (ParseOperationType::reduce, 71);
			table [68] [Symbol::statement_end].override (ParseOperationType::reduce, 71);
			table [69].resize (symbol_count);
			table [69] [Symbol::rscope].override (ParseOperationType::reduce, 72);
			table [69] [Symbol::statement_end].override (ParseOperationType::reduce, 72);
			table [70].resize (symbol_count);
			table [70] [Symbol::rscope].override (ParseOperationType::reduce, 73);
			table [70] [Symbol::statement_end].override (ParseOperationType::reduce, 73);
			table [71].resize (symbol_count);
			table [71] [Symbol::rscope].override (ParseOperationType::reduce, 67);
			table [71] [Symbol::statement_end].override (ParseOperationType::reduce, 67);
			table [72].resize (symbol_count);
			table [72] [Symbol::rscope].override (ParseOperationType::reduce, 68);
			table [72] [Symbol::statement_end].override (ParseOperationType::reduce, 68);
			table [73].resize (symbol_count);
			table [73] [Symbol::rparen].override (ParseOperationType::reduce, 22);
			table [74].resize (symbol_count);
			table [74] [Symbol::lparen].override (ParseOperationType::shift, 103);
			table [74] [Symbol::rparen].override (ParseOperationType::reduce, 26);
			table [74] [Symbol::lbrack].override (ParseOperationType::shift, 104);
			table [74] [Symbol::oper_union].override (ParseOperationType::shift, 107);
			table [75].resize (symbol_count);
			table [75] [Symbol::lparen].override (ParseOperationType::reduce, 35);
			table [75] [Symbol::rparen].override (ParseOperationType::reduce, 35);
			table [75] [Symbol::lbrack].override (ParseOperationType::reduce, 35);
			table [75] [Symbol::oper_union].override (ParseOperationType::reduce, 35);
			table [76].resize (symbol_count);
			table [76] [Symbol::lparen].override (ParseOperationType::reduce, 37);
			table [76] [Symbol::lbrack].override (ParseOperationType::reduce, 37);
			table [76] [Symbol::constant_number].override (ParseOperationType::reduce, 37);
			table [76] [Symbol::literalized_number].override (ParseOperationType::reduce, 37);
			table [76] [Symbol::constant_float].override (ParseOperationType::reduce, 37);
			table [76] [Symbol::constant_text].override (ParseOperationType::reduce, 37);
			table [76] [Symbol::identifier].override (ParseOperationType::reduce, 37);
			table [77].resize (symbol_count);
			table [77] [Symbol::lparen].override (ParseOperationType::reduce, 38);
			table [77] [Symbol::lbrack].override (ParseOperationType::reduce, 38);
			table [77] [Symbol::constant_number].override (ParseOperationType::reduce, 38);
			table [77] [Symbol::literalized_number].override (ParseOperationType::reduce, 38);
			table [77] [Symbol::constant_float].override (ParseOperationType::reduce, 38);
			table [77] [Symbol::constant_text].override (ParseOperationType::reduce, 38);
			table [77] [Symbol::identifier].override (ParseOperationType::reduce, 38);
			table [78].resize (symbol_count);
			table [78] [Symbol::lparen].override (ParseOperationType::reduce, 39);
			table [78] [Symbol::lbrack].override (ParseOperationType::reduce, 39);
			table [78] [Symbol::constant_number].override (ParseOperationType::reduce, 39);
			table [78] [Symbol::literalized_number].override (ParseOperationType::reduce, 39);
			table [78] [Symbol::constant_float].override (ParseOperationType::reduce, 39);
			table [78] [Symbol::constant_text].override (ParseOperationType::reduce, 39);
			table [78] [Symbol::identifier].override (ParseOperationType::reduce, 39);
			table [79].resize (symbol_count);
			table [79] [Symbol::lparen].override (ParseOperationType::reduce, 40);
			table [79] [Symbol::lbrack].override (ParseOperationType::reduce, 40);
			table [79] [Symbol::constant_number].override (ParseOperationType::reduce, 40);
			table [79] [Symbol::literalized_number].override (ParseOperationType::reduce, 40);
			table [79] [Symbol::constant_float].override (ParseOperationType::reduce, 40);
			table [79] [Symbol::constant_text].override (ParseOperationType::reduce, 40);
			table [79] [Symbol::identifier].override (ParseOperationType::reduce, 40);
			table [80].resize (symbol_count);
			table [80] [Symbol::lparen].override (ParseOperationType::reduce, 41);
			table [80] [Symbol::lbrack].override (ParseOperationType::reduce, 41);
			table [80] [Symbol::constant_number].override (ParseOperationType::reduce, 41);
			table [80] [Symbol::literalized_number].override (ParseOperationType::reduce, 41);
			table [80] [Symbol::constant_float].override (ParseOperationType::reduce, 41);
			table [80] [Symbol::constant_text].override (ParseOperationType::reduce, 41);
			table [80] [Symbol::identifier].override (ParseOperationType::reduce, 41);
			table [81].resize (symbol_count);
			table [81] [Symbol::lparen].override (ParseOperationType::reduce, 42);
			table [81] [Symbol::lbrack].override (ParseOperationType::reduce, 42);
			table [81] [Symbol::constant_number].override (ParseOperationType::reduce, 42);
			table [81] [Symbol::literalized_number].override (ParseOperationType::reduce, 42);
			table [81] [Symbol::constant_float].override (ParseOperationType::reduce, 42);
			table [81] [Symbol::constant_text].override (ParseOperationType::reduce, 42);
			table [81] [Symbol::identifier].override (ParseOperationType::reduce, 42);
			table [82].resize (symbol_count);
			table [82] [Symbol::lparen].override (ParseOperationType::reduce, 43);
			table [82] [Symbol::lbrack].override (ParseOperationType::reduce, 43);
			table [82] [Symbol::constant_number].override (ParseOperationType::reduce, 43);
			table [82] [Symbol::literalized_number].override (ParseOperationType::reduce, 43);
			table [82] [Symbol::constant_float].override (ParseOperationType::reduce, 43);
			table [82] [Symbol::constant_text].override (ParseOperationType::reduce, 43);
			table [82] [Symbol::identifier].override (ParseOperationType::reduce, 43);
			table [83].resize (symbol_count);
			table [83] [Symbol::lparen].override (ParseOperationType::reduce, 44);
			table [83] [Symbol::lbrack].override (ParseOperationType::reduce, 44);
			table [83] [Symbol::constant_number].override (ParseOperationType::reduce, 44);
			table [83] [Symbol::literalized_number].override (ParseOperationType::reduce, 44);
			table [83] [Symbol::constant_float].override (ParseOperationType::reduce, 44);
			table [83] [Symbol::constant_text].override (ParseOperationType::reduce, 44);
			table [83] [Symbol::identifier].override (ParseOperationType::reduce, 44);
			table [84].resize (symbol_count);
			table [84] [Symbol::lparen].override (ParseOperationType::reduce, 45);
			table [84] [Symbol::lbrack].override (ParseOperationType::reduce, 45);
			table [84] [Symbol::constant_number].override (ParseOperationType::reduce, 45);
			table [84] [Symbol::literalized_number].override (ParseOperationType::reduce, 45);
			table [84] [Symbol::constant_float].override (ParseOperationType::reduce, 45);
			table [84] [Symbol::constant_text].override (ParseOperationType::reduce, 45);
			table [84] [Symbol::identifier].override (ParseOperationType::reduce, 45);
			table [85].resize (symbol_count);
			table [85] [Symbol::lparen].override (ParseOperationType::reduce, 46);
			table [85] [Symbol::lbrack].override (ParseOperationType::reduce, 46);
			table [85] [Symbol::constant_number].override (ParseOperationType::reduce, 46);
			table [85] [Symbol::literalized_number].override (ParseOperationType::reduce, 46);
			table [85] [Symbol::constant_float].override (ParseOperationType::reduce, 46);
			table [85] [Symbol::constant_text].override (ParseOperationType::reduce, 46);
			table [85] [Symbol::identifier].override (ParseOperationType::reduce, 46);
			table [86].resize (symbol_count);
			table [86] [Symbol::lparen].override (ParseOperationType::reduce, 47);
			table [86] [Symbol::lbrack].override (ParseOperationType::reduce, 47);
			table [86] [Symbol::constant_number].override (ParseOperationType::reduce, 47);
			table [86] [Symbol::literalized_number].override (ParseOperationType::reduce, 47);
			table [86] [Symbol::constant_float].override (ParseOperationType::reduce, 47);
			table [86] [Symbol::constant_text].override (ParseOperationType::reduce, 47);
			table [86] [Symbol::identifier].override (ParseOperationType::reduce, 47);
			table [87].resize (symbol_count);
			table [87] [Symbol::lparen].override (ParseOperationType::reduce, 48);
			table [87] [Symbol::lbrack].override (ParseOperationType::reduce, 48);
			table [87] [Symbol::constant_number].override (ParseOperationType::reduce, 48);
			table [87] [Symbol::literalized_number].override (ParseOperationType::reduce, 48);
			table [87] [Symbol::constant_float].override (ParseOperationType::reduce, 48);
			table [87] [Symbol::constant_text].override (ParseOperationType::reduce, 48);
			table [87] [Symbol::identifier].override (ParseOperationType::reduce, 48);
			table [88].resize (symbol_count);
			table [88] [Symbol::lparen].override (ParseOperationType::reduce, 49);
			table [88] [Symbol::lbrack].override (ParseOperationType::reduce, 49);
			table [88] [Symbol::constant_number].override (ParseOperationType::reduce, 49);
			table [88] [Symbol::literalized_number].override (ParseOperationType::reduce, 49);
			table [88] [Symbol::constant_float].override (ParseOperationType::reduce, 49);
			table [88] [Symbol::constant_text].override (ParseOperationType::reduce, 49);
			table [88] [Symbol::identifier].override (ParseOperationType::reduce, 49);
			table [89].resize (symbol_count);
			table [89] [Symbol::lparen].override (ParseOperationType::reduce, 50);
			table [89] [Symbol::lbrack].override (ParseOperationType::reduce, 50);
			table [89] [Symbol::constant_number].override (ParseOperationType::reduce, 50);
			table [89] [Symbol::literalized_number].override (ParseOperationType::reduce, 50);
			table [89] [Symbol::constant_float].override (ParseOperationType::reduce, 50);
			table [89] [Symbol::constant_text].override (ParseOperationType::reduce, 50);
			table [89] [Symbol::identifier].override (ParseOperationType::reduce, 50);
			table [90].resize (symbol_count);
			table [90] [Symbol::lparen].override (ParseOperationType::reduce, 51);
			table [90] [Symbol::lbrack].override (ParseOperationType::reduce, 51);
			table [90] [Symbol::constant_number].override (ParseOperationType::reduce, 51);
			table [90] [Symbol::literalized_number].override (ParseOperationType::reduce, 51);
			table [90] [Symbol::constant_float].override (ParseOperationType::reduce, 51);
			table [90] [Symbol::constant_text].override (ParseOperationType::reduce, 51);
			table [90] [Symbol::identifier].override (ParseOperationType::reduce, 51);
			table [91].resize (symbol_count);
			table [91] [Symbol::lparen].override (ParseOperationType::reduce, 52);
			table [91] [Symbol::lbrack].override (ParseOperationType::reduce, 52);
			table [91] [Symbol::constant_number].override (ParseOperationType::reduce, 52);
			table [91] [Symbol::literalized_number].override (ParseOperationType::reduce, 52);
			table [91] [Symbol::constant_float].override (ParseOperationType::reduce, 52);
			table [91] [Symbol::constant_text].override (ParseOperationType::reduce, 52);
			table [91] [Symbol::identifier].override (ParseOperationType::reduce, 52);
			table [92].resize (symbol_count);
			table [92] [Symbol::rparen].override (ParseOperationType::shift, 108);
			table [93].resize (symbol_count);
			table [93] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [93] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [93] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [93] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [93] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [93] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [93] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [93] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [93] [Symbol::nterm_item].override (ParseOperationType::go_to, 95);
			table [93] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [93] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [93] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [93] [Symbol::nterm_union].override (ParseOperationType::go_to, 109);
			table [94].resize (symbol_count);
			table [94] [Symbol::lparen].override (ParseOperationType::reduce, 60);
			table [94] [Symbol::rscope].override (ParseOperationType::reduce, 60);
			table [94] [Symbol::lbrack].override (ParseOperationType::reduce, 60);
			table [94] [Symbol::statement_end].override (ParseOperationType::reduce, 60);
			table [95].resize (symbol_count);
			table [95] [Symbol::lparen].override (ParseOperationType::shift, 103);
			table [95] [Symbol::lbrack].override (ParseOperationType::shift, 104);
			table [95] [Symbol::rbrack].override (ParseOperationType::reduce, 54);
			table [95] [Symbol::oper_union].override (ParseOperationType::shift, 110);
			table [96].resize (symbol_count);
			table [96] [Symbol::rbrack].override (ParseOperationType::shift, 111);
			table [97].resize (symbol_count);
			table [97] [Symbol::identifier].override (ParseOperationType::shift, 112);
			table [98].resize (symbol_count);
			table [98] [Symbol::identifier].override (ParseOperationType::shift, 113);
			table [99].resize (symbol_count);
			table [99] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [99] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [99] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [99] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [99] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [99] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [99] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [99] [Symbol::oper_plus].override (ParseOperationType::shift, 76);
			table [99] [Symbol::oper_minus].override (ParseOperationType::shift, 77);
			table [99] [Symbol::oper_star].override (ParseOperationType::shift, 78);
			table [99] [Symbol::oper_slash].override (ParseOperationType::shift, 79);
			table [99] [Symbol::oper_percent].override (ParseOperationType::shift, 80);
			table [99] [Symbol::oper_left_left].override (ParseOperationType::shift, 81);
			table [99] [Symbol::oper_right_right].override (ParseOperationType::shift, 82);
			table [99] [Symbol::oper_accent].override (ParseOperationType::shift, 83);
			table [99] [Symbol::oper_stand].override (ParseOperationType::shift, 84);
			table [99] [Symbol::oper_ampersand].override (ParseOperationType::shift, 85);
			table [99] [Symbol::oper_equal].override (ParseOperationType::shift, 86);
			table [99] [Symbol::oper_not_equal].override (ParseOperationType::shift, 87);
			table [99] [Symbol::oper_less_than].override (ParseOperationType::shift, 88);
			table [99] [Symbol::oper_less_than_equal].override (ParseOperationType::shift, 89);
			table [99] [Symbol::oper_greater_than].override (ParseOperationType::shift, 90);
			table [99] [Symbol::oper_greater_than_equal].override (ParseOperationType::shift, 91);
			table [99] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [99] [Symbol::nterm_item].override (ParseOperationType::go_to, 114);
			table [99] [Symbol::nterm_paren_oper].override (ParseOperationType::go_to, 115);
			table [99] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [99] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [99] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [99] [Symbol::nterm_any_oper].override (ParseOperationType::go_to, 93);
			table [100].resize (symbol_count);
			table [100] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [100] [Symbol::lscope].override (ParseOperationType::shift, 40);
			table [100] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [100] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [100] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [100] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [100] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [100] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [100] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [100] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [100] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [100] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [100] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [100] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [100] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [100] [Symbol::keyword_goto].override (ParseOperationType::shift, 55);
			table [100] [Symbol::keyword_seg].override (ParseOperationType::shift, 56);
			table [100] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [100] [Symbol::keyword_while].override (ParseOperationType::shift, 57);
			table [100] [Symbol::keyword_if].override (ParseOperationType::shift, 58);
			table [100] [Symbol::nterm_declare].override (ParseOperationType::go_to, 59);
			table [100] [Symbol::nterm_code].override (ParseOperationType::go_to, 116);
			table [100] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [100] [Symbol::nterm_location].override (ParseOperationType::go_to, 64);
			table [100] [Symbol::nterm_item].override (ParseOperationType::go_to, 60);
			table [100] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [100] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [100] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [100] [Symbol::nterm_if].override (ParseOperationType::go_to, 118);
			table [100] [Symbol::nterm_if_else].override (ParseOperationType::go_to, 119);
			table [100] [Symbol::nterm_simple_stmt].override (ParseOperationType::go_to, 117);
			table [100] [Symbol::nterm_goto_stmt].override (ParseOperationType::go_to, 68);
			table [100] [Symbol::nterm_seg_stmt].override (ParseOperationType::go_to, 69);
			table [100] [Symbol::nterm_vardef].override (ParseOperationType::go_to, 70);
			table [101].resize (symbol_count);
			table [101] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [101] [Symbol::lscope].override (ParseOperationType::shift, 40);
			table [101] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [101] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [101] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [101] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [101] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [101] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [101] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [101] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [101] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [101] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [101] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [101] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [101] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [101] [Symbol::keyword_goto].override (ParseOperationType::shift, 55);
			table [101] [Symbol::keyword_seg].override (ParseOperationType::shift, 56);
			table [101] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [101] [Symbol::keyword_while].override (ParseOperationType::shift, 57);
			table [101] [Symbol::keyword_if].override (ParseOperationType::shift, 58);
			table [101] [Symbol::nterm_declare].override (ParseOperationType::go_to, 59);
			table [101] [Symbol::nterm_code].override (ParseOperationType::go_to, 120);
			table [101] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [101] [Symbol::nterm_location].override (ParseOperationType::go_to, 64);
			table [101] [Symbol::nterm_item].override (ParseOperationType::go_to, 60);
			table [101] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [101] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [101] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [101] [Symbol::nterm_if].override (ParseOperationType::go_to, 122);
			table [101] [Symbol::nterm_if_else].override (ParseOperationType::go_to, 123);
			table [101] [Symbol::nterm_simple_stmt].override (ParseOperationType::go_to, 121);
			table [101] [Symbol::nterm_goto_stmt].override (ParseOperationType::go_to, 68);
			table [101] [Symbol::nterm_seg_stmt].override (ParseOperationType::go_to, 69);
			table [101] [Symbol::nterm_vardef].override (ParseOperationType::go_to, 70);
			table [102].resize (symbol_count);
			table [102] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [102] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [102] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [102] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [102] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [102] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [102] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [102] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [102] [Symbol::nterm_item].override (ParseOperationType::go_to, 124);
			table [102] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [102] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [102] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [103].resize (symbol_count);
			table [103] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [103] [Symbol::rparen].override (ParseOperationType::shift, 125);
			table [103] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [103] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [103] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [103] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [103] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [103] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [103] [Symbol::oper_plus].override (ParseOperationType::shift, 76);
			table [103] [Symbol::oper_minus].override (ParseOperationType::shift, 77);
			table [103] [Symbol::oper_star].override (ParseOperationType::shift, 78);
			table [103] [Symbol::oper_slash].override (ParseOperationType::shift, 79);
			table [103] [Symbol::oper_percent].override (ParseOperationType::shift, 80);
			table [103] [Symbol::oper_left_left].override (ParseOperationType::shift, 81);
			table [103] [Symbol::oper_right_right].override (ParseOperationType::shift, 82);
			table [103] [Symbol::oper_accent].override (ParseOperationType::shift, 83);
			table [103] [Symbol::oper_stand].override (ParseOperationType::shift, 84);
			table [103] [Symbol::oper_ampersand].override (ParseOperationType::shift, 85);
			table [103] [Symbol::oper_equal].override (ParseOperationType::shift, 86);
			table [103] [Symbol::oper_not_equal].override (ParseOperationType::shift, 87);
			table [103] [Symbol::oper_less_than].override (ParseOperationType::shift, 88);
			table [103] [Symbol::oper_less_than_equal].override (ParseOperationType::shift, 89);
			table [103] [Symbol::oper_greater_than].override (ParseOperationType::shift, 90);
			table [103] [Symbol::oper_greater_than_equal].override (ParseOperationType::shift, 91);
			table [103] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [103] [Symbol::nterm_item].override (ParseOperationType::go_to, 95);
			table [103] [Symbol::nterm_paren_oper].override (ParseOperationType::go_to, 126);
			table [103] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [103] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [103] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [103] [Symbol::nterm_any_oper].override (ParseOperationType::go_to, 93);
			table [103] [Symbol::nterm_union].override (ParseOperationType::go_to, 127);
			table [104].resize (symbol_count);
			table [104] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [104] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [104] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [104] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [104] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [104] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [104] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [104] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [104] [Symbol::nterm_item].override (ParseOperationType::go_to, 128);
			table [104] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [104] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [104] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [105].resize (symbol_count);
			table [105] [Symbol::identifier].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_shader].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_float].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_bool].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_void].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_int].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_nat].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_var].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_goto].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_graphic].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::keyword_interface].override (ParseOperationType::reduce, 63);
			table [105] [Symbol::ending].override (ParseOperationType::reduce, 63);
			table [106].resize (symbol_count);
			table [106] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [106] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [106] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [106] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [106] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [106] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [106] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [106] [Symbol::statement_end].override (ParseOperationType::shift, 54);
			table [106] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [106] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [106] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [106] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [106] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [106] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [106] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [106] [Symbol::keyword_goto].override (ParseOperationType::shift, 55);
			table [106] [Symbol::keyword_seg].override (ParseOperationType::shift, 56);
			table [106] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [106] [Symbol::keyword_while].override (ParseOperationType::shift, 57);
			table [106] [Symbol::keyword_if].override (ParseOperationType::shift, 58);
			table [106] [Symbol::nterm_declare].override (ParseOperationType::go_to, 59);
			table [106] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [106] [Symbol::nterm_location].override (ParseOperationType::go_to, 64);
			table [106] [Symbol::nterm_item].override (ParseOperationType::go_to, 60);
			table [106] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [106] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [106] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [106] [Symbol::nterm_stmtunion].override (ParseOperationType::go_to, 129);
			table [106] [Symbol::nterm_stmt].override (ParseOperationType::go_to, 66);
			table [106] [Symbol::nterm_if].override (ParseOperationType::go_to, 71);
			table [106] [Symbol::nterm_if_else].override (ParseOperationType::go_to, 72);
			table [106] [Symbol::nterm_simple_stmt].override (ParseOperationType::go_to, 67);
			table [106] [Symbol::nterm_goto_stmt].override (ParseOperationType::go_to, 68);
			table [106] [Symbol::nterm_seg_stmt].override (ParseOperationType::go_to, 69);
			table [106] [Symbol::nterm_vardef].override (ParseOperationType::go_to, 70);
			table [107].resize (symbol_count);
			table [107] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [107] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [107] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [107] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [107] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [107] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [107] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [107] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [107] [Symbol::keyword_goto].override (ParseOperationType::shift, 9);
			table [107] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [107] [Symbol::nterm_declare].override (ParseOperationType::go_to, 130);
			table [107] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [107] [Symbol::nterm_location].override (ParseOperationType::go_to, 18);
			table [107] [Symbol::nterm_defassignunion].override (ParseOperationType::go_to, 131);
			table [108].resize (symbol_count);
			table [108] [Symbol::lparen].override (ParseOperationType::reduce, 27);
			table [108] [Symbol::rscope].override (ParseOperationType::reduce, 27);
			table [108] [Symbol::lbrack].override (ParseOperationType::reduce, 27);
			table [108] [Symbol::statement_end].override (ParseOperationType::reduce, 27);
			table [109].resize (symbol_count);
			table [109] [Symbol::rparen].override (ParseOperationType::reduce, 36);
			table [110].resize (symbol_count);
			table [110] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [110] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [110] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [110] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [110] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [110] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [110] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [110] [Symbol::nterm_location].override (ParseOperationType::go_to, 75);
			table [110] [Symbol::nterm_item].override (ParseOperationType::go_to, 95);
			table [110] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [110] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [110] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [110] [Symbol::nterm_union].override (ParseOperationType::go_to, 132);
			table [111].resize (symbol_count);
			table [111] [Symbol::lparen].override (ParseOperationType::reduce, 59);
			table [111] [Symbol::rscope].override (ParseOperationType::reduce, 59);
			table [111] [Symbol::lbrack].override (ParseOperationType::reduce, 59);
			table [111] [Symbol::statement_end].override (ParseOperationType::reduce, 59);
			table [112].resize (symbol_count);
			table [112] [Symbol::rscope].override (ParseOperationType::reduce, 75);
			table [112] [Symbol::statement_end].override (ParseOperationType::reduce, 75);
			table [113].resize (symbol_count);
			table [113] [Symbol::rscope].override (ParseOperationType::reduce, 76);
			table [113] [Symbol::statement_end].override (ParseOperationType::reduce, 76);
			table [114].resize (symbol_count);
			table [114] [Symbol::lparen].override (ParseOperationType::shift, 103);
			table [114] [Symbol::rparen].override (ParseOperationType::shift, 133);
			table [114] [Symbol::lbrack].override (ParseOperationType::shift, 104);
			table [115].resize (symbol_count);
			table [115] [Symbol::rparen].override (ParseOperationType::shift, 134);
			table [116].resize (symbol_count);
			table [116] [Symbol::rscope].override (ParseOperationType::reduce, 93);
			table [116] [Symbol::statement_end].override (ParseOperationType::reduce, 93);
			table [117].resize (symbol_count);
			table [117] [Symbol::rscope].override (ParseOperationType::reduce, 92);
			table [117] [Symbol::statement_end].override (ParseOperationType::reduce, 92);
			table [118].resize (symbol_count);
			table [118] [Symbol::rscope].override (ParseOperationType::reduce, 91);
			table [118] [Symbol::statement_end].override (ParseOperationType::reduce, 91);
			table [119].resize (symbol_count);
			table [119] [Symbol::rscope].override (ParseOperationType::reduce, 99);
			table [119] [Symbol::statement_end].override (ParseOperationType::reduce, 99);
			table [120].resize (symbol_count);
			table [120] [Symbol::rscope].override (ParseOperationType::reduce, 81);
			table [120] [Symbol::statement_end].override (ParseOperationType::reduce, 81);
			table [120] [Symbol::keyword_else].override (ParseOperationType::shift, 135);
			table [121].resize (symbol_count);
			table [121] [Symbol::rscope].override (ParseOperationType::reduce, 80);
			table [121] [Symbol::statement_end].override (ParseOperationType::reduce, 80);
			table [121] [Symbol::keyword_else].override (ParseOperationType::shift, 136);
			table [122].resize (symbol_count);
			table [122] [Symbol::rscope].override (ParseOperationType::reduce, 79);
			table [122] [Symbol::statement_end].override (ParseOperationType::reduce, 79);
			table [123].resize (symbol_count);
			table [123] [Symbol::keyword_else].override (ParseOperationType::shift, 137);
			table [124].resize (symbol_count);
			table [124] [Symbol::lparen].override (ParseOperationType::shift, 103);
			table [124] [Symbol::rscope].override (ParseOperationType::reduce, 78);
			table [124] [Symbol::lbrack].override (ParseOperationType::shift, 104);
			table [124] [Symbol::statement_end].override (ParseOperationType::reduce, 78);
			table [125].resize (symbol_count);
			table [125] [Symbol::lparen].override (ParseOperationType::reduce, 57);
			table [125] [Symbol::rscope].override (ParseOperationType::reduce, 57);
			table [125] [Symbol::lbrack].override (ParseOperationType::reduce, 57);
			table [125] [Symbol::statement_end].override (ParseOperationType::reduce, 57);
			table [126].resize (symbol_count);
			table [126] [Symbol::rparen].override (ParseOperationType::shift, 138);
			table [127].resize (symbol_count);
			table [127] [Symbol::rparen].override (ParseOperationType::shift, 139);
			table [128].resize (symbol_count);
			table [128] [Symbol::lparen].override (ParseOperationType::shift, 103);
			table [128] [Symbol::lbrack].override (ParseOperationType::shift, 104);
			table [128] [Symbol::rbrack].override (ParseOperationType::shift, 140);
			table [129].resize (symbol_count);
			table [129] [Symbol::rscope].override (ParseOperationType::reduce, 65);
			table [130].resize (symbol_count);
			table [130] [Symbol::oper_assign].override (ParseOperationType::shift, 45);
			table [131].resize (symbol_count);
			table [131] [Symbol::rparen].override (ParseOperationType::reduce, 25);
			table [132].resize (symbol_count);
			table [132] [Symbol::rbrack].override (ParseOperationType::reduce, 53);
			table [133].resize (symbol_count);
			table [133] [Symbol::lparen].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::lscope].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::lbrack].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::constant_number].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::literalized_number].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::constant_float].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::constant_text].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::identifier].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_shader].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_float].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_bool].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_void].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_int].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_nat].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_var].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_goto].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_seg].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_interface].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_while].override (ParseOperationType::reduce, 94);
			table [133] [Symbol::keyword_if].override (ParseOperationType::reduce, 94);
			table [134].resize (symbol_count);
			table [134] [Symbol::lparen].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::lscope].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::lbrack].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::constant_number].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::literalized_number].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::constant_float].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::constant_text].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::identifier].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_shader].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_float].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_bool].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_void].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_int].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_nat].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_var].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_goto].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_seg].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_interface].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_while].override (ParseOperationType::reduce, 95);
			table [134] [Symbol::keyword_if].override (ParseOperationType::reduce, 95);
			table [135].resize (symbol_count);
			table [135] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [135] [Symbol::lscope].override (ParseOperationType::shift, 40);
			table [135] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [135] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [135] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [135] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [135] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [135] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [135] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [135] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [135] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [135] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [135] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [135] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [135] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [135] [Symbol::keyword_goto].override (ParseOperationType::shift, 55);
			table [135] [Symbol::keyword_seg].override (ParseOperationType::shift, 56);
			table [135] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [135] [Symbol::keyword_while].override (ParseOperationType::shift, 57);
			table [135] [Symbol::keyword_if].override (ParseOperationType::shift, 58);
			table [135] [Symbol::nterm_declare].override (ParseOperationType::go_to, 59);
			table [135] [Symbol::nterm_code].override (ParseOperationType::go_to, 141);
			table [135] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [135] [Symbol::nterm_location].override (ParseOperationType::go_to, 64);
			table [135] [Symbol::nterm_item].override (ParseOperationType::go_to, 60);
			table [135] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [135] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [135] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [135] [Symbol::nterm_if].override (ParseOperationType::go_to, 143);
			table [135] [Symbol::nterm_if_else].override (ParseOperationType::go_to, 144);
			table [135] [Symbol::nterm_simple_stmt].override (ParseOperationType::go_to, 142);
			table [135] [Symbol::nterm_goto_stmt].override (ParseOperationType::go_to, 68);
			table [135] [Symbol::nterm_seg_stmt].override (ParseOperationType::go_to, 69);
			table [135] [Symbol::nterm_vardef].override (ParseOperationType::go_to, 70);
			table [136].resize (symbol_count);
			table [136] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [136] [Symbol::lscope].override (ParseOperationType::shift, 40);
			table [136] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [136] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [136] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [136] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [136] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [136] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [136] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [136] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [136] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [136] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [136] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [136] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [136] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [136] [Symbol::keyword_goto].override (ParseOperationType::shift, 55);
			table [136] [Symbol::keyword_seg].override (ParseOperationType::shift, 56);
			table [136] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [136] [Symbol::keyword_while].override (ParseOperationType::shift, 57);
			table [136] [Symbol::keyword_if].override (ParseOperationType::shift, 58);
			table [136] [Symbol::nterm_declare].override (ParseOperationType::go_to, 59);
			table [136] [Symbol::nterm_code].override (ParseOperationType::go_to, 145);
			table [136] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [136] [Symbol::nterm_location].override (ParseOperationType::go_to, 64);
			table [136] [Symbol::nterm_item].override (ParseOperationType::go_to, 60);
			table [136] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [136] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [136] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [136] [Symbol::nterm_if].override (ParseOperationType::go_to, 147);
			table [136] [Symbol::nterm_if_else].override (ParseOperationType::go_to, 148);
			table [136] [Symbol::nterm_simple_stmt].override (ParseOperationType::go_to, 146);
			table [136] [Symbol::nterm_goto_stmt].override (ParseOperationType::go_to, 68);
			table [136] [Symbol::nterm_seg_stmt].override (ParseOperationType::go_to, 69);
			table [136] [Symbol::nterm_vardef].override (ParseOperationType::go_to, 70);
			table [137].resize (symbol_count);
			table [137] [Symbol::lparen].override (ParseOperationType::shift, 47);
			table [137] [Symbol::lscope].override (ParseOperationType::shift, 40);
			table [137] [Symbol::lbrack].override (ParseOperationType::shift, 49);
			table [137] [Symbol::constant_number].override (ParseOperationType::shift, 50);
			table [137] [Symbol::literalized_number].override (ParseOperationType::shift, 51);
			table [137] [Symbol::constant_float].override (ParseOperationType::shift, 52);
			table [137] [Symbol::constant_text].override (ParseOperationType::shift, 53);
			table [137] [Symbol::identifier].override (ParseOperationType::shift, 25);
			table [137] [Symbol::keyword_shader].override (ParseOperationType::shift, 2);
			table [137] [Symbol::keyword_float].override (ParseOperationType::shift, 3);
			table [137] [Symbol::keyword_bool].override (ParseOperationType::shift, 4);
			table [137] [Symbol::keyword_void].override (ParseOperationType::shift, 5);
			table [137] [Symbol::keyword_int].override (ParseOperationType::shift, 6);
			table [137] [Symbol::keyword_nat].override (ParseOperationType::shift, 7);
			table [137] [Symbol::keyword_var].override (ParseOperationType::shift, 8);
			table [137] [Symbol::keyword_goto].override (ParseOperationType::shift, 55);
			table [137] [Symbol::keyword_seg].override (ParseOperationType::shift, 56);
			table [137] [Symbol::keyword_interface].override (ParseOperationType::shift, 11);
			table [137] [Symbol::keyword_while].override (ParseOperationType::shift, 57);
			table [137] [Symbol::keyword_if].override (ParseOperationType::shift, 58);
			table [137] [Symbol::nterm_declare].override (ParseOperationType::go_to, 59);
			table [137] [Symbol::nterm_code].override (ParseOperationType::go_to, 149);
			table [137] [Symbol::nterm_type].override (ParseOperationType::go_to, 17);
			table [137] [Symbol::nterm_location].override (ParseOperationType::go_to, 64);
			table [137] [Symbol::nterm_item].override (ParseOperationType::go_to, 60);
			table [137] [Symbol::nterm_call_item].override (ParseOperationType::go_to, 61);
			table [137] [Symbol::nterm_array_access].override (ParseOperationType::go_to, 62);
			table [137] [Symbol::nterm_array].override (ParseOperationType::go_to, 63);
			table [137] [Symbol::nterm_if].override (ParseOperationType::go_to, 151);
			table [137] [Symbol::nterm_if_else].override (ParseOperationType::go_to, 152);
			table [137] [Symbol::nterm_simple_stmt].override (ParseOperationType::go_to, 150);
			table [137] [Symbol::nterm_goto_stmt].override (ParseOperationType::go_to, 68);
			table [137] [Symbol::nterm_seg_stmt].override (ParseOperationType::go_to, 69);
			table [137] [Symbol::nterm_vardef].override (ParseOperationType::go_to, 70);
			table [138].resize (symbol_count);
			table [138] [Symbol::lparen].override (ParseOperationType::reduce, 56);
			table [138] [Symbol::rscope].override (ParseOperationType::reduce, 56);
			table [138] [Symbol::lbrack].override (ParseOperationType::reduce, 56);
			table [138] [Symbol::statement_end].override (ParseOperationType::reduce, 56);
			table [139].resize (symbol_count);
			table [139] [Symbol::lparen].override (ParseOperationType::reduce, 55);
			table [139] [Symbol::rscope].override (ParseOperationType::reduce, 55);
			table [139] [Symbol::lbrack].override (ParseOperationType::reduce, 55);
			table [139] [Symbol::statement_end].override (ParseOperationType::reduce, 55);
			table [140].resize (symbol_count);
			table [140] [Symbol::lparen].override (ParseOperationType::reduce, 58);
			table [140] [Symbol::rscope].override (ParseOperationType::reduce, 58);
			table [140] [Symbol::lbrack].override (ParseOperationType::reduce, 58);
			table [140] [Symbol::statement_end].override (ParseOperationType::reduce, 58);
			table [141].resize (symbol_count);
			table [141] [Symbol::rscope].override (ParseOperationType::reduce, 90);
			table [141] [Symbol::statement_end].override (ParseOperationType::reduce, 90);
			table [142].resize (symbol_count);
			table [142] [Symbol::rscope].override (ParseOperationType::reduce, 87);
			table [142] [Symbol::statement_end].override (ParseOperationType::reduce, 87);
			table [143].resize (symbol_count);
			table [143] [Symbol::rscope].override (ParseOperationType::reduce, 84);
			table [143] [Symbol::statement_end].override (ParseOperationType::reduce, 84);
			table [144].resize (symbol_count);
			table [144] [Symbol::rscope].override (ParseOperationType::reduce, 98);
			table [144] [Symbol::statement_end].override (ParseOperationType::reduce, 98);
			table [145].resize (symbol_count);
			table [145] [Symbol::rscope].override (ParseOperationType::reduce, 89);
			table [145] [Symbol::statement_end].override (ParseOperationType::reduce, 89);
			table [146].resize (symbol_count);
			table [146] [Symbol::rscope].override (ParseOperationType::reduce, 86);
			table [146] [Symbol::statement_end].override (ParseOperationType::reduce, 86);
			table [147].resize (symbol_count);
			table [147] [Symbol::rscope].override (ParseOperationType::reduce, 83);
			table [147] [Symbol::statement_end].override (ParseOperationType::reduce, 83);
			table [148].resize (symbol_count);
			table [148] [Symbol::rscope].override (ParseOperationType::reduce, 97);
			table [148] [Symbol::statement_end].override (ParseOperationType::reduce, 97);
			table [149].resize (symbol_count);
			table [149] [Symbol::rscope].override (ParseOperationType::reduce, 88);
			table [149] [Symbol::statement_end].override (ParseOperationType::reduce, 88);
			table [150].resize (symbol_count);
			table [150] [Symbol::rscope].override (ParseOperationType::reduce, 85);
			table [150] [Symbol::statement_end].override (ParseOperationType::reduce, 85);
			table [151].resize (symbol_count);
			table [151] [Symbol::rscope].override (ParseOperationType::reduce, 82);
			table [151] [Symbol::statement_end].override (ParseOperationType::reduce, 82);
			table [152].resize (symbol_count);
			table [152] [Symbol::rscope].override (ParseOperationType::reduce, 96);
			table [152] [Symbol::statement_end].override (ParseOperationType::reduce, 96);
			
		}
	} // namespace Parser
} // namespace Alton
